name: sariska_media_flutter_sdk
description: Sariska Media Flutter SDK provides powerful Dart API's for developing real-time applications for audio and video calling.
version: 0.0.7
homepage: https://github.com/SariskaIO/Sariska-Media-Flutter-SDK

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: io.sariska.sariska_media_flutter_sdk
        pluginClass: SariskaMediaTransportPlugin
      ios:
        pluginClass: SariskaMediaTransportFlutterPlugin

androidPackage: io.sariska.sariska_media_flutter_sdk
androidPermissions:
  - android.permission.CAMERA
  - android.permission.RECORD_AUDIO
  - android.permission.MODIFY_AUDIO_SETTINGS
  - android.permission.INTERNET

ios:
  pluginClass: SariskaMediaTransportFlutterPlugin
  permissions:
    - camera
    - microphone
    - internet

  # Mention that this plugin supports Android and iOS currently.
  platforms:
    - android
    - ios
